<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\CreoToolkit.Sdk\CreoToolkit.Sdk.csproj" />
    <ProjectReference Include="..\..\..\src\CreoToolkit.App\CreoToolkit.App.csproj" />
  </ItemGroup>
</Project>
